#ifndef CONSTANTES_H_
#define CONSTANTES_H_

#define ON 1
#define OFF 0
#define NUM_TORPEDOS 4
#define NUM_PROJETEIS 200
#define TORPEDO_INCREMENT 0.7
#define TORPEDO_INCREMENT_VERTICAL 0.07
#define TORPEDO_INCREMENT_HORIZONTAL 0.07
#define TORPEDO_POSITION_Y -4.89
#define PROJETIL_INCREMENT 0.7
#define TEMPO_TOTAL 10 // Em segundos
#define NUM_ALVOS 5

#endif // CONSTANTES_H_
