#ifndef CONSTANTES_H_
#define CONSTANTES_H_

#define ON 1
#define OFF 0
#define TORPEDO 1
#define PROJETIL 2
#define NUM_TORPEDOS 4
#define NUM_PROJETEIS 200
#define TORPEDO_INCREMENT 0.7
#define TORPEDO_INCREMENT_VERTICAL 0.07
#define TORPEDO_INCREMENT_HORIZONTAL 0.1
#define TORPEDO_POSITION_Y -4.89
#define PROJETIL_INCREMENT 0.7
#define TEMPO_TOTAL 3000 // Em segundos
#define NUM_ALVOS 5
#define PROJETEIS_ATINGIDOS 2
#define TORPEDOS_ATINGIDOS 50

#endif // CONSTANTES_H_
