#ifndef CONSTANTES_H_
#define CONSTANTES_H_

#define ON 1
#define OFF 0
#define NUM_TORPEDOS 4
#define NUM_PROJETEIS 200
#define TORPEDO_INCREMENT 0.7
#define TORPEDO_INCREMENT_VERTICAL 0.035
#define TORPEDO_INCREMENT_HORIZONTAL 0.05
#define PROJETIL_INCREMENT 0.7
#define PROJETIL_INCREMENT_VERTICAL 0.1

#endif // CONSTANTES_H_
